INSERT INTO CONTACT (ID, ADDRESS_LINE1, ADDRESS_LINE2, CITY, COUNTRY, CREATED_DATE, EMAIL, FIRST_NAME, LAST_NAME, PHONE, STATE, UPDATED_DATE, ZIP_CODE )
VALUES (10001,'BODE RD', '', 'SCHAUMBURG', 'USA', SYSDATE(), 'AGAUL@ABC.COM', 'ASTRIX', 'GAUL', '847-754-3434', 'IL', SYSDATE(), '60173');

INSERT INTO CONTACT (ID, ADDRESS_LINE1, ADDRESS_LINE2, CITY, COUNTRY, CREATED_DATE, EMAIL, FIRST_NAME, LAST_NAME, PHONE, STATE, UPDATED_DATE, ZIP_CODE )
VALUES (10002,'1266 IRVING PARK RD', '', 'HANOVER PARK', 'USA', SYSDATE(), 'BPAMPAS@ABC.COM', 'BOB', 'PAMPAS', '847-754-2222', 'IL', SYSDATE(), '60133');


INSERT INTO CONTACT (ID, ADDRESS_LINE1, ADDRESS_LINE2, CITY, COUNTRY, CREATED_DATE, EMAIL, FIRST_NAME, LAST_NAME, PHONE, STATE, UPDATED_DATE, ZIP_CODE )
VALUES (10003,'1405 S PARK AVE', 'APT 345', 'STREAMWOOD', 'USA', SYSDATE(), 'CSAVANAH@ABC.COM', 'CAT', 'SAVANAH', '847-754-4444', 'IL', SYSDATE(), '60107');


INSERT INTO CONTACT (ID, ADDRESS_LINE1, ADDRESS_LINE2, CITY, COUNTRY, CREATED_DATE, EMAIL, FIRST_NAME, LAST_NAME, PHONE, STATE, UPDATED_DATE, ZIP_CODE )
VALUES (10004,'875 PACIFIC AVE', 'APT 345', 'HOFFMAN ESTATES', 'USA', SYSDATE(), 'RSTEPPE@ABC.COM', 'ROD', 'STEPPE', '847-754-7676', 'IL', SYSDATE(), '60169');

INSERT INTO CONTACT (ID, ADDRESS_LINE1, ADDRESS_LINE2, CITY, COUNTRY, CREATED_DATE, EMAIL, FIRST_NAME, LAST_NAME, PHONE, STATE, UPDATED_DATE, ZIP_CODE )
VALUES (10005,'123 Business', '', 'Ft Collins', 'USA', SYSDATE(), 'rbhorn@rockies.com', 'Ram', 'Bighorn', '970-491-2345', 'CO', SYSDATE(), '80521');

INSERT INTO CONTACT (ID, ADDRESS_LINE1, ADDRESS_LINE2, CITY, COUNTRY, CREATED_DATE, EMAIL, FIRST_NAME, LAST_NAME, PHONE, STATE, UPDATED_DATE, ZIP_CODE )
VALUES (10006,'123 Main', '', 'Ft Collins', 'USA', SYSDATE(), 'phorn@rockies.com', 'Prong', 'Horn', '970-491-3456', 'CO', SYSDATE(), '80521');